### ISSUE TITLE
Incompatible with coverage 5.0

### ISSUE THREAD

**Issue by goerz** [computationalmodelling/nbval#129]
It seems like `nbval` does not work with the just released coverage 5.0 package: https://travis-ci.org/qucontrol/krotov/jobs/625049383

**Comment by eric-wieser** [comment]
The error is:
```

    def _make_suffix(cov):
        """Create a suffix for nbval data file depending on pytest-cov config."""
        # Check if coverage object has data_suffix:
>       if cov and cov.data_suffix is not None:
E       AttributeError: 'Coverage' object has no attribute 'data_suffix'
```

**Comment by takluyver** [comment]
PR #130 pins the version of coverage to avoid this problem. But we should work out a proper fix and unpin it again, so I'll leave this issue open.

**Comment by eric-wieser** [comment]
See https://github.com/nedbat/coveragepy/issues/882#issuecomment-566552214 for more information

**Comment by mloubout** [comment]
Hello, we ran into issue in our CI due to the new `coverage < 5.0` requirement that make our installation crash. Is there any timeline concerning that issue?

**Comment by mloubout** [comment]
Any update on this one?

**Comment by vidartf** [comment]
I had a look again to figure out what the code is doing. Basically, the code is trying to tell whether we are being run with the [`Central`](https://github.com/pytest-dev/pytest-cov/blob/87a11732e76658244ed23d7f38e93adb19c4a795/src/pytest_cov/engine.py#L171) pytest-cov engine, or the [`DistWorker`](https://github.com/pytest-dev/pytest-cov/blob/87a11732e76658244ed23d7f38e93adb19c4a795/src/pytest_cov/engine.py#L296) (previously `DistSlave`) pytest-cov engine.

The easiest solution is probably to say "we only support the central engine", and get rid of this code.

**Comment by vidartf** [comment]
Looking at it further, it is might just be best to drop the coverage support.

**Comment by eric-wieser** [comment]
Dropping support for coverage entirely would be a real shame :(

**Comment by vidartf** [comment]
I made a fix PR, but its all dependent on pytest-cov remaining somewhat stable.

**Comment by goerz** [comment]
For what it’s worth, I depend on coverage reports including code that ran only due to nbval (alongside “normal” tests). So I very much hope you’re not dropping coverage support.

**Comment by vidartf** [comment]
@goerz Would you be able to test that the PR (#134) works as expected for you?

**Comment by goerz** [comment]
I'll give it a try soon...

**Comment by goerz** [comment]
Looks good! 👍

**Comment by vidartf** [comment]
Released as 0.9.5
